pr: none

pool:
  vmImage: 'windows-latest'

steps:
- checkout: self
  clean: "true"
  fetchDepth: "1"

- script: |
    setx JAVA_HOME "C:\Program Files\OpenJDK"
    echo "checking env vars..."
    echo %JAVA_HOME%
    echo %PATH%
    echo "refreshing env..."
    call refreshenv
    echo %JAVA_HOME%
    echo %PATH%
    echo "done"

  displayName: "Install OpenJDK"

- script: |
    echo "checking env vars..."
    echo %JAVA_HOME%
    echo %PATH%
    echo "refreshing env..."
    call refreshenv
    echo %JAVA_HOME%
    echo %PATH%
    echo "done"

- task: Maven@3
  inputs:
    goals: 'compile'

#    choco install openjdk

