pr: none

pool:
  vmImage: 'windows-latest'

steps:
- checkout: self
  clean: "true"
  fetchDepth: "1"

- script: |
    choco install openjdk
    echo "checking env vars..."
    echo %JAVA_HOME%
    echo %PATH%
    echo "refreshing env..."
    refreshenv
    echo %JAVA_HOME%
    echo %PATH%
    echo "done"

  displayName: "Install OpenJDK"

- script: |
    echo "checking env vars..."
    echo %JAVA_HOME%
    echo %PATH%
    echo "refreshing env..."
    refreshenv
    echo %JAVA_HOME%
    echo %PATH%
    echo "done"

#- task: Maven@3
#  inputs:
#    javaHomeOption: 'JDKVersion'
#    jdkVersionOption: '1.15'
#    jdkArchitectureOption: 'x64'
#    publishJUnitResults: true
#    testResultsFiles: '**/surefire-reports/TEST-*.xml'
#    goals: 'test'

